"""System prompt and the portfolio context block (PLAN.md §9 steps 1 and 3).

The context is rendered as compact text rather than raw JSON: the model reads it more
reliably, and it costs a fraction of the tokens of a pretty-printed portfolio dump on every
single turn.
"""

from __future__ import annotations

SYSTEM_PROMPT = """\
You are FinAlly, an AI trading assistant embedded in a simulated trading workstation.

Your job:
- Analyse portfolio composition, risk concentration and P&L.
- Suggest trades with explicit reasoning grounded in the numbers you are given.
- Execute trades when the user asks or agrees to one.
- Manage the watchlist proactively when it helps the user.
- Be concise and data-driven. Prefer specific figures over adjectives.

Rules you must not break:
- Respond ONLY with JSON matching the required schema: `message`, `trades`, \
`watchlist_changes`.
- `message` is the text the user reads. Never put JSON inside it.
- Put a trade in `trades` ONLY when the user has asked for it or agreed to it. Proposing an
  idea is a `message`; acting on it is a `trade`. When in doubt, propose and ask.
- Trades execute immediately at the current market price, with no confirmation step. There
  are no fees, no limit orders and no short selling: you can only sell shares already held.
- Quantities may be fractional. Never request a trade you can see is unaffordable — the
  cash balance and holdings below are authoritative.
- A ticker you trade that is not on the watchlist is added to it automatically.
- This is a simulated portfolio with virtual money. Never claim to give real financial
  advice, and never invent prices, news or fundamentals you were not given.
"""

_MODE_NOTES = {
    "live": "LIVE — real market prices polled from the provider.",
    "anchored": (
        "ANCHORED — real previous closes anchor each ticker, but intraday movement is "
        "simulated. Do not describe intraday moves as real market events."
    ),
    "simulated": (
        "SIMULATED — every price is generated by a local simulator. Do not describe any "
        "move as a real market event or attribute it to news."
    ),
}


def render_context(portfolio: dict, watchlist: list[dict], mode: str) -> str:
    """The portfolio context block: cash, positions with P&L, watchlist, total value."""
    lines = [
        f"MARKET DATA MODE: {_MODE_NOTES.get(mode, mode)}",
        "",
        "ACCOUNT",
        f"  Cash balance:    ${portfolio['cash_balance']:,.2f}",
        f"  Positions value: ${portfolio['positions_value']:,.2f}",
        f"  Total value:     ${portfolio['total_value']:,.2f}",
        f"  Started with:    ${portfolio['starting_cash']:,.2f}",
        f"  Total return:    ${portfolio['total_return']:,.2f} "
        f"({portfolio['total_return_pct']:+.2f}%)",
        "",
        "POSITIONS",
    ]

    if portfolio["positions"]:
        for holding in portfolio["positions"]:
            price = f"${holding['price']:,.2f}" if holding["priced"] else "unpriced"
            lines.append(
                f"  {holding['ticker']:<6} qty {holding['quantity']:<12,.4f} "
                f"avg ${holding['avg_cost']:,.2f}  now {price}  "
                f"value ${holding['market_value']:,.2f}  "
                f"P&L ${holding['unrealized_pnl']:,.2f} "
                f"({holding['unrealized_pnl_pct']:+.2f}%)  "
                f"weight {holding['weight'] * 100:.1f}%"
            )
    else:
        lines.append("  (none — the portfolio is entirely cash)")

    lines += ["", "WATCHLIST"]
    if watchlist:
        for entry in watchlist:
            if entry.get("priced"):
                lines.append(
                    f"  {entry['ticker']:<6} ${entry['price']:,.2f}  "
                    f"day {entry['change_pct']:+.2f}%"
                )
            else:
                lines.append(f"  {entry['ticker']:<6} (no price yet)")
    else:
        lines.append("  (empty)")

    return "\n".join(lines)


def build_messages(context: str, history: list[dict], user_message: str) -> list[dict]:
    """System message, portfolio context, conversation history, then the new message.

    Context is a separate system message rather than being glued onto the prompt so the
    numbers are unmistakably current state and not something the user typed.
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "system", "content": f"Current portfolio state:\n\n{context}"},
    ]
    messages += [{"role": row["role"], "content": row["content"]} for row in history]
    messages.append({"role": "user", "content": user_message})
    return messages
