"use client";

import type { LivePortfolio } from "@/lib/derive";
import { money, percent, signedMoney, toneClass } from "@/lib/format";
import type { ConnectionState, Mode } from "@/lib/types";

const CONNECTION: Record<ConnectionState, { dot: string; label: string; text: string }> = {
  open: { dot: "bg-up", label: "LIVE FEED", text: "text-up" },
  connecting: { dot: "bg-muted", label: "CONNECTING", text: "text-muted" },
  reconnecting: { dot: "bg-accent animate-pulse", label: "RECONNECTING", text: "text-accent" },
  closed: { dot: "bg-down", label: "DISCONNECTED", text: "text-down" },
};

// PLAN.md §6 is explicit that the UI must surface the real mode rather than claiming
// "live" unconditionally — a Basic-tier key produces real anchors with simulated motion,
// and saying otherwise would misrepresent the data the user is trading on.
const MODE: Record<Mode, { label: string; title: string; className: string }> = {
  live: {
    label: "LIVE",
    title: "Real market prices, polled from the provider.",
    className: "border-up/50 text-up",
  },
  anchored: {
    label: "ANCHORED",
    title:
      "Real previous closes anchor each ticker; intraday movement is simulated (Basic-tier key).",
    className: "border-accent/50 text-accent",
  },
  simulated: {
    label: "SIMULATED",
    title: "Every price is generated by the built-in market simulator.",
    className: "border-brand/50 text-brand",
  },
};

function Stat({
  label,
  value,
  tone = "text-ink",
  size = "text-sm",
  testId,
}: {
  label: string;
  value: string;
  tone?: string;
  size?: string;
  testId?: string;
}) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-2xs uppercase tracking-[0.14em] text-faint">{label}</span>
      <span className={`tnum ${size} ${tone}`} data-testid={testId}>
        {value}
      </span>
    </div>
  );
}

export function Header({
  portfolio,
  mode,
  connection,
  healthy,
  onReset,
}: {
  portfolio: LivePortfolio | null;
  mode: Mode | null;
  connection: ConnectionState;
  healthy: boolean;
  onReset: () => void;
}) {
  const status = CONNECTION[connection];
  const modeBadge = mode ? MODE[mode] : null;

  return (
    <header className="flex items-center gap-6 border-b border-edge bg-panel px-4 py-2">
      <div className="flex items-baseline gap-2">
        <span className="text-lg font-bold tracking-tight text-ink">
          Fin<span className="text-accent">Ally</span>
        </span>
        <span className="hidden text-2xs uppercase tracking-[0.2em] text-faint lg:inline">
          AI Trading Workstation
        </span>
      </div>

      <div className="flex flex-1 items-center gap-6">
        <Stat
          label="Total Value"
          value={money(portfolio?.total_value)}
          size="text-lg font-semibold"
          testId="stat-total-value"
        />
        <Stat label="Cash" value={money(portfolio?.cash_balance)} testId="stat-cash" />
        <Stat
          label="Total Return"
          value={
            portfolio
              ? `${signedMoney(portfolio.total_return)} (${percent(portfolio.total_return_pct)})`
              : "—"
          }
          tone={toneClass(portfolio?.total_return)}
        />
        <Stat
          label="Unrealized"
          value={signedMoney(portfolio?.unrealized_pnl)}
          tone={toneClass(portfolio?.unrealized_pnl)}
        />
      </div>

      <div className="flex items-center gap-3">
        {modeBadge && (
          <span
            title={modeBadge.title}
            className={`border px-2 py-1 text-2xs font-semibold tracking-widest ${modeBadge.className}`}
          >
            {modeBadge.label}
          </span>
        )}

        <div
          className="flex items-center gap-2"
          title={healthy ? "Market data task is running" : "Market data task is unhealthy"}
        >
          <span
            className={`h-2 w-2 rounded-full ${status.dot}`}
            data-testid="connection-dot"
            data-state={connection}
          />
          <span
            className={`text-2xs font-semibold tracking-widest ${status.text}`}
            data-testid="connection-label"
          >
            {healthy ? status.label : "DEGRADED"}
          </span>
        </div>

        <button className="btn btn-ghost" onClick={onReset} title="Reset to $10,000 and the seed watchlist">
          Reset
        </button>
      </div>
    </header>
  );
}
