<#
.SYNOPSIS
    Adopt the reconstructed real book as the live FinAlly portfolio.

.DESCRIPTION
    Fetches the reconstructed book from GET /api/history/session and restores it through
    POST /api/session, so the live portfolio becomes the real one: real share equivalents,
    real USD cost bases, real cash.

    It posts to /api/session rather than placing market buys because that is the only endpoint
    that can set an exact quantity AND an exact average cost, in one transaction, under the
    same trade lock as a trade. Replaying the ledger as buys would fill every leg at today's
    price and rewrite every cost basis with it - which would make the unrealised P&L on the
    restored book meaningless.

    The document is fetched from the app rather than recomputed here on purpose: the
    reconstruction math then lives in exactly one place instead of forking into a CLI copy
    that drifts from the curve the chart is drawing.

    Instruments with no US daily closes - the Argentine bonds and locally-listed equities -
    are reported and excluded, because they have no price the app could ever show.

    This REPLACES positions, trades and P&L history (chat history is kept), so it prompts
    unless you pass --yes. Requires the app running and backend\calibration\ledger.json
    generated by import_broker_with_dates.ps1.

.EXAMPLE
    .\scripts\load_history.ps1 --dry-run     # print the book, change nothing
    .\scripts\load_history.ps1 --yes         # replace the portfolio
#>

# See equal_weight_portfolio.ps1 for why there is no param block and no ErrorActionPreference.

. "$PSScriptRoot\lib_portfolio_tool.ps1"

Invoke-PortfolioTool -Command "load_history" -Arguments $args
